### ISSUE TITLE
Don't opened and visible seem redundant?

### ISSUE THREAD

**Issue by NoahCardoza** [fattihkoca/vuejs-overlay#1]
I'm not sure if I'm missing something here, but it would seem that both `opened` and `visible` are required to display a model? Why not only use one or the other?

**Comment by fattihkoca** [comment]
You can think of `visible` as "loaded".  
Let me explain in detail with an example:
You submitted the open request in the component and set it to `opened = true`. After then you started remote data retrieve process (such as ajax, axios). Meanwhile, this component shows the loading animation. Then when loaded you set it to `visible = true`.

**Comment by NoahCardoza** [comment]
Oh I see, makes sense. Maybe it would be better renamed as loading then? But keep opened around for backwards compatibility?

Up to you. Other than that I really like the styling/layout. So far I’ve just been passing the same variable to both props since I’m not using it to load any data from a request.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fattihkoca** [comment]
Actually, I was in a dilemma about naming at the beginning. Because there is also a loading situation inside :)

Thank you so much for your great thoughts.
